# Generated by Django 3.0.14 on 2022-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(default='Lorem ipsum', max_length=300),
        ),
        migrations.AlterField(
            model_name='objectlist',
            name='name',
            field=models.CharField(default='Objects', max_length=200),
        ),
    ]
