# Generated by Django 3.0.14 on 2022-09-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asgard', '0002_auto_20220921_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='objectlist',
        ),
        migrations.DeleteModel(
            name='ObjectList',
        ),
    ]
